import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/universal/Sidebar";
import SearchBar from "@/components/universal/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Collabor8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark-900 max-h-screen overflow-hidden text-white-500`}>
        <div className="flex">
          <Sidebar />
          <div className="w-4/5">
            <SearchBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
